# Builder
FROM rust:1.85-alpine AS builder

RUN apk update && \
  apk add --no-cache musl-dev

WORKDIR /app

COPY . .

RUN cargo build --release

# Final
FROM alpine:3.21

COPY --from=builder /app/target/release/btc_rpc_proxy /usr/bin/btc_rpc_proxy

RUN chmod +x /usr/bin/btc_rpc_proxy

SHELL [ "/bin/ash", "-c" ]
ENTRYPOINT chmod 600 /etc/btc_rpc_proxy/btc_rpc_proxy.toml \
  && exec /usr/bin/btc_rpc_proxy \
    --conf /etc/btc_rpc_proxy/btc_rpc_proxy.toml
